on: [push,pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master
    
    # dotnet build and publish
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o myapp 

    # Azure login
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Define secret variable in repository settings as per action documentation
   
    # deploy web app
    - uses: azure/webapps-deploy@v1
      with: 
        app-name: mydotnetcoreapp  # Replace with your app name
        package: './myapp'

    # Azure logout 
    - name: logout
      run: |
        az logout