on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master

    # Azure login
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Define secret variable in repository settings as per action documentation
    
    # install dependencies, build, and test
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    # Archive built app
    - name: archive myapp
      run: |
       zip -r myapp.zip .
   
    # deploy web app
    - uses: azure/appservice-actions/webapp@master
      with: 
        app-name: mynodeapp   # Replace with your app name
        package: './myapp.zip'

    # Azure logout 
    - name: logout
      run: |
        az logout
